### ISSUE TITLE
Multiple errors in make_a_face.py

### ISSUE THREAD

**Issue by alkatraz445** [nabanaa/FaceReco#10]
Nie wiem czemu, jest tak dużo errorów, wszystko poinstalowałem

#### pomoc
<img width="1144" alt="Zrzut ekranu 2024-01-20 o 18 57 09" src="https://github.com/nabanaa/FaceReco/assets/32413541/e6af5851-194c-44e1-8425-a6c8804567d1">

**Comment by Nestrion** [comment]
W pierwszej linijce pisze że data nie jest częścią modułu cv2, czy CameraCapture.py nie wyrzuca ci tych błędów? Ponieważ jest tam również kod zawierający cv2.data.
![image](https://github.com/nabanaa/FaceReco/assets/76516946/c18a4afa-3948-4bce-b4d7-0ce2a0347c38)

**Comment by alkatraz445** [comment]
<img width="771" alt="Zrzut ekranu 2024-01-21 o 15 46 40" src="https://github.com/nabanaa/FaceReco/assets/32413541/a5c4e2c2-6a71-45c4-a376-92b091ea05ef">

**Comment by Nestrion** [comment]
Teraz widzę że ja mam wersje 4.8.1.78, a nie  4.9.0.80 z requirements.txt, może w tej nowszej wersji przenieśli cv2.data gdzieś indziej, jak wrócę do domu to sie temu przyjrzę.

**Comment by TymonPawelczyk** [comment]
Następny error
![image](https://github.com/nabanaa/FaceReco/assets/92690905/e9cacc7a-6fa5-4680-9802-8cdb64c711a2)

**Comment by Nestrion** [comment]
@alkatraz445 powiedz czy zmiana z `opencv-python` na `opencv-contrib-python` coś dała, bo u mnie działa i nie jestem w stanie zreplikować błędu.

**Comment by alkatraz445** [comment]
> @alkatraz445 powiedz czy zmiana z `opencv-python` na `opencv-contrib-python` coś dała, bo u mnie działa i nie jestem w stanie zreplikować błędu.

Zmiana na `opencv-contrib-python` jak na razie nic nie dała. Szukam dalej.

**Comment by TymonPawelczyk** [comment]
W moim przypadku pobranie '''opencv-contrib-python''' pomogło.

**Comment by Nestrion** [comment]
@alkatraz445 Mógłbyś mi podać swoją wersję pythona? Chcę zmatchować środowisko do twojego, może wtedy u mnie też wystąpią te błędy.

**Comment by Nestrion** [comment]
Teraz jak o tym myśle to najrozsądniej chyba zrobić żeby aplikacja sie pobierała z własnym virtual environmentem.

**Comment by alkatraz445** [comment]
> Teraz jak o tym myśle to najrozsądniej chyba zrobić żeby aplikacja sie pobierała z własnym virtual environmentem. 

Jestem za tym, będzie najrozsądniej jak najbardziej ją odizolować od systemu użytkownika. Poszukam jakichś rozwiązań

**Comment by alkatraz445** [comment]
> @alkatraz445 Mógłbyś mi podać swoją wersję pythona? Chcę zmatchować środowisko do twojego, może wtedy u mnie też wystąpią te błędy.

Wyślę Ci mojego venv

**Comment by Nestrion** [comment]
> > Teraz jak o tym myśle to najrozsądniej chyba zrobić żeby aplikacja sie pobierała z własnym virtual environmentem.
> 
> Jestem za tym, będzie najrozsądniej jak najbardziej ją odizolować od systemu użytkownika. Poszukam jakichś rozwiązań

Spokojnie, już nad tym siedzę.

**Comment by Nestrion** [comment]
@alkatraz445 Dodałem swoje rozwiązanie na nowy branch, proszę powiedz mi czy błędy z tego wątku dalej będą wyskakiwały, i czy takie rozwiązanie ogółem może być.

**Comment by alkatraz445** [comment]
> @alkatraz445 Dodałem swoje rozwiązanie na nowy branch, proszę powiedz mi czy błędy z tego wątku dalej będą wyskakiwały, i czy takie rozwiązanie ogółem może być.

Zrób pull request na tego brancha i tam go obczaję
