### ISSUE TITLE
Smudge Error. This repository is over it's data quota.

### ISSUE THREAD

**Issue by Nestrion** [nabanaa/FaceReco#11]
Czy problem zaprezentowany na poniższym screenie dotyczy tylko mnie? Nie pozwala mi zpullować przez to.

![image](https://github.com/nabanaa/FaceReco/assets/76516946/b16532c7-5b7b-423b-bda3-286711f12be7)

EDIT:
git lfs uninstall w skrócie naprawia ten problem, zamykam issue

**Comment by alkatraz445** [comment]
Otwieram ponownie bo @p-j-o-t-e-r natrafił na ten sam problem

**Comment by Nestrion** [comment]
Właśnie też ten problem daje do myślenia czy ma sens trzymanie wszystkich modeli na gitcie, bo ich jeszcze przybędzie, a to data quota wynosi 1GiB. Jest jeszcze opcja mniej radykalna, żeby chociaż na maina wszystkich nie uploadować tylko zrobić osobny branch z modelami, a w mainie tylko jakieś 3 zostawić.

**Comment by alkatraz445** [comment]
Uważam, że należy zrobić jakieś zewnętrzne (np. Google Drive) repo, które będzie zawierało te gigantyczne pliki i pozwalało je zaciągnąć już podczas odpalania programu.

Wychodzi na to, że to będzie dosyć duża zmiana. **Zalecam stworzenie osobnego branch'a**

**Comment by alkatraz445** [comment]
Został nam tylko ten smugde error do ogarnięcia porządnie i możemy wypuszczać `v0.1.0`.

Jaką bierzemy ścieżkę?

Mamy do wyboru

1. Dropbox/GDrive
2. Wrócić do Git LFS i zmagać się z data capem
3. Umieścić tylko 1 mały model i dać znać userom, że `u nas działa. sami sobie zrobicie swoje`

@Nestrion @p-mika-gsuite 
Proszę o wypowiedź

**Comment by p-mika-gsuite** [comment]
W sumie  to nic nie szkodzi, żeby w naszym repo była opcja LFS, z jakimś 1 małym modelem. I w sumie zastanawiam się, czy da się w sposób darmowy połączyć jakąkolwiek chmurową technologię z naszą appką, bo wcześniej już miałem z tym problem tworząc CameraCapture.py

**Comment by Nestrion** [comment]
Zgodzę się z Piotrkiem - jeden mały default w mainie brzmi odpowiednio. Do tego jakiś gdrive z którego można pobrać sobie reszte modeli które mamy, najlepiej za  pomocą przygotowane skryptu znajdującego się w repo, który je umieści od razu do models.

**Comment by alkatraz445** [comment]
> Zgodzę się z Piotrkiem - jeden mały default w mainie brzmi odpowiednio. Do tego jakiś gdrive z którego można pobrać sobie reszte modeli które mamy, najlepiej za pomocą przygotowane skryptu znajdującego się w repo, który je umieści od razu do folderu `Models`.

Genialnie, zabieram się za skrypt i drive. Nie wiem jeszcze, czy użyje `dropbox`, czy `google drive`, ale coś dziś będzie w pull request
