### ISSUE TITLE
Add tests to make_a_face.py

### ISSUE THREAD

**Issue by alkatraz445** [nabanaa/FaceReco#15]
Przydałoby się stworzyć jakieś testy kompatybilne z `pytest`, żebyśmy mieli jakąkolwiek kontrole nad przepływem danych

**Comment by Nestrion** [comment]
Dobra, zabieram się za to.

**Comment by Nestrion** [comment]
Dobra skończyłem proste testy, są już na mainie.

**Comment by alkatraz445** [comment]
Jeśli nie będzie pull request to zamykam issue. Świetna robota

**Comment by alkatraz445** [comment]
Otwieram ponownie. bo nie mogę znaleźć w main tych testów

**Comment by Nestrion** [comment]
Właśnie widziałem że porządki zrobiłeś, chyba najprościej będzie jak kopie mojego maina wrzucę na osobny branch?

**Comment by alkatraz445** [comment]
> Właśnie widziałem że porządki zrobiłeś, chyba najprościej będzie jak kopie mojego maina wrzucę na osobny branch?

Proszę porównaj to z tym co na pull request wrzuciłem
