### ISSUE TITLE
Delete unneeded comments

### ISSUE THREAD

**Issue by alkatraz445** [nabanaa/FaceReco#2]
### Description
I have noticed an unusual amount of comments from the user "Piotr Mika" across various repositories. The comments seem to be unrelated to the code or the issues being discussed, and they might be considered as spam.

### Steps to Reproduce
1. Visit [repository](https://github.com/nabanaa/FaceReco)
2. Scroll through the comments section.
3. Observe multiple comments from the user "Piotr Mika."

### Expected Behavior
GitHub discussions should focus on relevant topics related to the codebase, issues, or pull requests. Excessive and unrelated comments can be disruptive to the community.

### Proposed Solution
Consider moderating or restricting comments from the user "Piotr Mika" if they continue to post unrelated or excessive comments. This will help maintain a more focused and productive discussion environment.

Thank you for your attention to this matter.

**Comment by 2kadrenojunkie** [comment]
i've been looking for almost 5 minutes now and have not found the aforementioned spam or signs that there was spam that had been removed. was it just solved really quick or what? this issue seems to be either mistaken or malicious in nature. accidentally posted in wrong repo perhaps?

**Comment by alkatraz445** [comment]
> i've been looking for almost 5 minutes now and have not found the aforementioned spam or signs that there was spam that had been removed. was it just solved really quick or what? this issue seems to be either mistaken or malicious in nature. accidentally posted in wrong repo perhaps?

Yes it was solved rather quickly
